# A dictionary of the clusters/environments that we can onboard applications into
clusters:
  # Name of the cluster/environment
  tools:
    # Master endpoint of the cluster (this must match what is defined for the cluster in ArgoCD)
    server: https://kubernetes.default.svc
    # Name of the cluster (this must match what is defined for the cluster in ArgoCD)
    name: in-cluster
  mgmt:
    server: https://kubernetes.default.svc
    name: tony-cluster


# A list of the projects that will be created in ArgoCD, a project will have multiple applications defined under it
projects:
# This is the name that will be used directly when creating the ArgoCD Project
- name: global
  # This is the description that will be used directly when creating the ArgoCD Project
  description: Project for apps which are deployed globally for clusters
  # A list of clusterResourceWhitelist items for this project, allows applications in this project to create cluster level resources specified
  # By default we do not allow applications to create any cluster level resources (only namespaced resources)
  # OPTIONAL
  clusterResourceWhitelistOverrides:
  - group: ''
    kind: Namespace
  # Override the allowed namespaces for applications
  # By default all namespaces for applications must begin with the name of the project
  # If you want applications in this project be able to deploy to any namespace the value must be literal "'*'"
  # OPTIONAL
  namespaceOverride: "'*'" 
  # A list of the applications i.e. a link from source to destinations
  # An ArgoCD application is created per application environment an application with no environments specified will not have any effect
  applications:
    # This name is used as part of the ArgoCD application name, which will be of the format:
    # {project.name}-{application.name}-{environment.name}
  - name: 'namespaces'
    # By default we look for environment folders in the root of the repository e.g. /dev /qal
    # This optional key allows you put application environment definitions into folders e.g. /pathPrefix/dev /pathPrefix/qal
    # OPTIONAL
    pathPrefix: global-applications
    # Specifies the repository that contains the deployment resources for this application
    # APPLICATION SPECIFIC NOTE: The namespaces "application" depends on this values.yaml file, so it co-exists in this repo
    repoURL: git@github.com:ake13/argocd-app-configs.git
    # Don't create a namespace for this application
    # Usually you want this if the namespace already exists (e.g. you're deploying to a system namespace, or some other preexisting names)
    # or if your application is made of purely non-namespaced resources
    dontCreateNamespace: true
    # List of environments/clusters for which an ArgoCD application (and namespace) will be created
    environments:
    - name: tony-cluster



# #### App1 and app2 belonging to "Team 1" will be deployed on demo namespace from the same repository
# - name: demo
#   description: "Demo app1 and app2"
#   applications:
#     - name: app1
#       pathPrefix: apps
#       repoURL: git@github.com:verint-globaldevops/demo-app1.git
#       environments:
#         - name: tony-cluster

#     - name: app2
#       pathPrefix: apps
#       repoURL: git@github.com:verint-globaldevops/demo-app1.git
#       environments:
#         - name: tony-cluster

# # #### App3 belonging to "Team 2" will be deployed on demo3 namespace from another repository
# - name: demo3
#   description: "Demo app3"
#   applications:
#     - name: app3
#       pathPrefix: apps
#       repoURL: git@github.com:verint-globaldevops/demo-app3.git
#       environments:
#         - name: tony-cluster


