{{- define "app.namespaces" }}
  {{- $namespaces := dict }}
  {{- range $project_index, $project := .Values.projects }}
    {{- range $application_index, $application := $project.applications }}
      {{- range $environment_index, $environment := $application.environments }}
        {{- if eq $environment.name $.envName }}
          {{- if (not $application.dontCreateNamespace) }}
            {{- $namespace := $application.namespaceOverride | default $project.name }}
          {{- end }}  
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  {{- end }}
---  
  {{- end}}
{{- end }}
